### ISSUE TITLE
Footer for Author (for blog)

### ISSUE THREAD

**Issue by madrvojt** [XMDGCZ/XMDGCZ.github.io#15]
Add Footer in Blog page with author info

**Comment by malyda** [comment]
What information about the author should be displayed there? Except name, of course.

**Comment by madrvojt** [comment]
- Name
- Contact (Maybe)
- Short Bio (where, what, which technologies) - 500 characters max.
- Photo

**Comment by madrvojt** [comment]
Something like that http://prntscr.com/kucmjj

**Comment by madrvojt** [comment]
Done!
